### ISSUE TITLE
Spurious "invalid UTF-8 encoding" when using in Alire 2.0 crate

### ISSUE THREAD

**Issue by mgrojo** [pmderodat/ada-toml#13]
I'm using ada-toml in my utility [alr_appimage](https://github.com/mgrojo/alr-appimage), and I'm getting a weird error when processing a file in UTF-8 format, like https://github.com/jfuica/bingada/blob/master/alire.toml:
```
Error: while loading alire.toml: 5: 31: invalid UTF-8 encoding
```
I'm using latest version in Alire index (0.3.0).

Alire also uses this library to load the same file without problem.

Could it be that the default Alire switches are now not compatible with how this library is loading the file? I guess that in order to work like in Alire, this commit should be included and a new release made:

https://github.com/mosteo/ada-toml/commit/da4e59c382ceb0de6733d571ecbab7ea4919b33d

Is there any problem impending the merge of that change?

**Comment by pmderodat** [comment]
Hello,

https://github.com/mosteo/ada-toml/commit/da4e59c382ceb0de6733d571ecbab7ea4919b33d was actually merged into https://github.com/pmderodat/ada-toml more than a year ago (https://github.com/pmderodat/ada-toml/pull/11). The problem was just that I haven’t released ada-toml since then. I just released 0.4.0 to address this, and the new release was just accepted into Alire’s index (https://github.com/alire-project/alire-index/pull/1008), so this should be fine, now. Please let me know if not.

**Comment by mgrojo** [comment]
Hello @pmderodat,

Thanks, it's working now.

**Comment by pmderodat** [comment]
Great, thank you for letting me know!
