### ISSUE TITLE
Arrays and arrays of arrays

### ISSUE THREAD

**Issue by Fabien-Chouteau** [pmderodat/ada-toml#7]
I noticed some problems with arrays:

`echo 'a = ["a", "b"]' | obj-checkers/ada_toml_decode` -> OK

`echo 'a = [0, 1]' | obj-checkers/ada_toml_decode` -> `1:6: invalid token`

`echo 'a = [[0], [1]]' | obj-checkers/ada_toml_decode` -> `1:7: invalid token`

`echo 'a = [["a"], ["b"]]' | obj-checkers/ada_toml_decode` -> OK

**Comment by pmderodat** [comment]
Thank you very much for reporting this parser bug! It should now be fixed on the master branch. :-)

**Comment by mgrojo** [comment]
Could this be updated in the Alire catalog, which is still version 0.1.0? I think I'm stumbled upon it, because it says "invalid token" when there are zeros in an array. My code is [here](https://github.com/mgrojo/play_2048/pull/3/files#diff-7521cc9c55e5c25659963c86cf5e77f811d49e221378057e8799bc06ce9d9158).

Thanks for your work!

**Comment by Fabien-Chouteau** [comment]
@mgrojo v0.2 is now available in Alire https://github.com/alire-project/alire-index/pull/315

**Comment by mgrojo** [comment]
Thanks!

**Comment by pmderodat** [comment]
Thanks Fabien for taking care of this while I’m mostly unavailable! ;-)
